services:
  - type: web
    name: live-blog-websocket
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server/y-websocket-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true 